version: '3.8'

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    env_file: .env # Φορτώνει τις μεταβλητές από το .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./site:/srv  # Πρόσθεσε αυτή τη γραμμή για να σερβίρετε μια ιστοσελίδα.
      - ./data:/data # Bind mount για μόνιμη αποθήκευση
      - ./config:/config
    networks:
      - web

# docker network create web
networks:
  web:
    external: true

