services:
  db:
    image: postgres:16-alpine
    container_name: nextcloud_db
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=<postgrs_password> # Βάλε έναν κωδικό
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
    volumes:
      - /srv/nextcloud/db:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: nextcloud_redis
    restart: unless-stopped
    networks:
      - backend

  app:
    image: nextcloud:fpm-alpine
    container_name: nextcloud_app
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=<postgrs_password>
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.iosifidis.gr
      - TRUSTED_PROXIES=172.16.0.0/12 # Εδώ λέμε στο Nextcloud να εμπιστεύεται το container του Caddy
      - OVERWRITEPROTOCOL=https
    volumes:
      - /srv/nextcloud/app:/var/www/html # Εδώ μπαίνει ο κώδικας (index.php κλπ)
      - /srv/nextcloud/nc_data:/var/www/data # Εδώ θα μπούν τα αρχεία των χρηστών (ΦΩΤΟ, ΕΓΓΡΑΦΑ)
    networks:
      - backend
      - web

 # --- ΠΡΟΣΘΗΚΕΣ ΓΙΑ ΤΟ TALK ---

  nc-talk:
    container_name: talk_hpb
    image: ghcr.io/nextcloud-releases/aio-talk:latest
    init: true
    ports:
      - "3478:3478/tcp"  # Πόρτες για STUN/TURN
      - "3478:3478/udp"
      - "8081:8081/tcp"  # Πόρτα για το Signaling (εσωτερικά)
    environment:
      - NC_DOMAIN=cloud.iosifidis.gr
      - TALK_HOST=cloud.iosifidis.gr
      # openssl rand -hex 32
      - TURN_SECRET=<Ο_ΚΩΔΙΚΟΣ_TURN_ΠΟΥ_ΔΗΜΙΟΥΡΓΗΣΑΤΕ>
      - SIGNALING_SECRET=<Ο_ΚΩΔΙΚΟΣ_SIGNALING_ΠΟΥ_ΔΗΜΙΟΥΡΓΗΣΑΤΕ>
      - INTERNAL_SECRET=<Ο_ΚΩΔΙΚΟΣ_INTERNAL_ΠΟΥ_ΔΗΜΙΟΥΡΓΗΣΑΤΕ>
      - TZ=Europe/Athens
      - TALK_PORT=3478
    restart: unless-stopped
    networks: # <--- ΠΡΟΣΘΗΚΗ ΕΔΩ
        - web    # <--- Προσθέστε το στο ίδιο δίκτυο με το Caddy

networks:
  backend:
    driver: bridge
  web:
    external: true

